Feature/13 fix fetch def
yochimonji/bifb pull request #17
Opened 2021-09-17 03:16 UTC by ltoppyl

fetch系の関数で、条件を絞り込んでデータを取得した場合に、末尾のオブジェクトしか表示できないバグの修正が完了しました。

fetch関数の方はシンプルにして、returnされた側でうまくデータを取得するような動きにしました。
returnされた先での各データの取得方法については、コメント分のところに書いています。

2021-09-17 08:13 UTC, ltoppyl commented
API_KEYに関する修正を行いました。

2021-09-17 09:03 UTC, yochimonji requested changes
今までで見逃してたところがまあまああったので修正お願い
- postProduct関数からpostTags関数を呼び出すようにNotionで指定してたと思うので修正お願いします
- タグコレクションに各タグが何個登録されているかの情報がないと思うのでそれもお願いします
- fetchProducts関数の条件式に日本語使ってるけど英語に変えましょー（一般的に英語な気がする）
- 認識のすり合わせがしたいんだけど、ユーザーページでフィードバックを選択した際に何が表示される予定？自分は作品一覧が出た来るつもりだったけど、プログラム的にはフィードバック一覧が表示される感じになってたからどっちかなと。

以下は確認事項
- 投稿したアプリを編集と削除する関数を忘れてた。編集するときはpostProduct関数に編集フラグでも立てるか別の関数を作るかどっちにしようか？
- いいねについてはこれからよね？

2021-09-17 09:22 UTC, ltoppyl commented
- 「postProduct関数からpostTags関数を呼び出すようにNotionで指定してたと思うので修正お願いします」
→ 作品を投稿する際に、選択していたタグが存在していなかったら追加するという認識でいいですか？？ 
    (それなら、すぐできます)
- Userページでフィードバックを選択したときは、自分がフィードバックした作品が表示されるつもりです。
  自分がどの作品にフィードバックしてるかは、feedback情報に入っているので、自分がfeedbackしてる作品のIDを取得→その作品IDの作品情報を取得という流れになると思うので、フェードバックを選択→作品情報がreturnされるっていう流れになるようにしておきます。

- 編集とか削除とかは、別の関数にしたほうがシンプルでわかりやすい気がします。
- いいねが押された時って、作品いいね数を増やす的な関数を作りますか？？

2021-09-17 12:38 UTC, yochimonji commented
- postTagsはそんな感じでおねがい
- ユーザーページのフィードバックもそれでお願い！
- いいねも関数を作ってもらおうかな、いいねが押されたら副作用でその関数を呼び出すイメージ

2021-09-17 12:40 UTC, ltoppyl commented
了解です！(`･ω･)ゞ

2021-09-17 17:45 UTC, ltoppyl commented
前のコメントにおける、追加・変更を実装しました。

作品を削除・編集した際にタグの使用された数の減少機能はついてないです。
これは別途別Issueにて対応します。

2021-09-18 12:27 UTC, yochimonji approved these changes
OKOK

2021-09-18 12:27 UTC, merged