ホーム画面で検索条件の✗ボタンを押したときの挙動
yochimonji/bifb pull request #74
Opened 2022-02-09 04:29 UTC by ltoppyl

## 🔨 変更内容
- 検索条件の部分の Close Button が押された場合の挙動の追加
具体的には、Close Button が押された場合に、検索条件がリセットされるようにする

## 📸 スクリーンショット

## ✅ 解決するイシュー
- close #62
## 🤝 関連するイシュー
- #62

2022-02-10 04:23 UTC, ltoppyl commented on src/components/Home/Home.tsx
> +      if (pe.type === "reload") {
![nits](https://img.shields.io/badge/review-nits-inactive.svg)
ここで、`Property 'type' does not exist on type 'PerformanceEntry' .` という警告が出てしまってますが、とりあえず動きます。

2022-02-10 04:27 UTC, ltoppyl commented on src/components/header/Header.tsx
> +          >
ヘッダーの部分の「BiFB」が押されたときに、`location.state` の値を空にしたくて、追加しました。
挙動としては想定どおりの動きをしていますが、<Link> の中の `href="/"` と `history.push("/")` が共存してるのが気持ち悪いので、この方法を採用する場合は、Link を Box なり、Button なりに変更したほうがいいかなーと思っています

2022-02-10 11:18 UTC, yochimonji requested changes
とりあえずコンフリクト起こしてるから修正お願い！！


それと検索タグをクリックしても検索結果に反映されないことがある。昨日自分が色々試してた時も同じ現象なったけど、検索タグタップするとなぜかリロード扱いになるからっぽい…
色々考えたけどリロードに関する実装を諦めて、ヘッダーの「BiFB」タップで戻れるならアプリの使用感的には問題ない！と我慢するしかないかも…
1. ホームでリロード
2. 検索ページに移動
3. 検索タグタップ
4. 反映されない？？？？
https://user-images.githubusercontent.com/54769623/153391760-3c1bb50e-1245-4407-b2ab-00b51ef90bca.mov

2022-02-10 11:18 UTC, yochimonji commented on src/components/Home/Home.tsx
> +      if (pe.type === "reload") {
めちゃくちゃ気持ち悪いけどこれで警告は消えたw
`if ((pe as unknown as {type: string}).type === "reload") {`

2022-02-10 11:18 UTC, yochimonji commented on src/components/header/Header.tsx
> +          >
これは元の自分の実装がゴミで混乱させてしまったと思う…
Chakra UIのドキュメントとZennの記事に従うとこれで`location.state`の値は空になると思う。こうすれば`useHistory()`は使う必要がなくなるよ。
```
import {Link as ReactLink} from "react-router-dom";

<Link as={ReactLink} to="/">
```

ちなみにstateにパラメータを持たせる場合はこんな感じ
```
<Link as={ReactLink} to={{pathname: "/", state: {param1: "a", param2: "b"} }}>
```

[Chakra UI で外部のルーティングライブラリの使い方](https://chakra-ui.com/docs/navigation/link#usage-with-routing-library)
[React Router のZennの記事](https://zenn.dev/h_yoshikawa0724/articles/2020-09-22-react-router#%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E5%BD%A2%E5%BC%8F)

2022-02-10 11:18 UTC, yochimonji commented on src/components/Home/SearchCondition.tsx
> +          }}
ここも`src/components/header/Header.tsx`で書いた方法と同じ方法に変えた方がいいかも

2022-02-10 11:49 UTC, ltoppyl commented on src/components/Home/SearchCondition.tsx
> +          }}
ここは、Close Button が押されたあとの動きなので、このままの方がいい気がします

2022-02-10 11:52 UTC, ltoppyl commented
リロードに対応した動きは一旦削除しました
一応 Issue を立てておきます！

2022-02-10 12:27 UTC, yochimonji reviewed
頭の中に？しかない

2022-02-10 12:27 UTC, yochimonji commented on src/components/Home/Home.tsx
> -    };
これを消すとメモリリークの警告が出ると思ってたんだけど出てこない…
一旦isMountedに関する全部のコード消そうか。消したらマージするね。

2022-02-10 12:27 UTC, yochimonji commented on src/components/Home/Home.tsx
>          }
isMountedの処理その２

2022-02-10 12:27 UTC, yochimonji commented on src/components/Home/Home.tsx
> +    const isMounted = true; // mount状態を監視する変数
isMountedに関する処理その１

2022-02-11 01:47 UTC, yochimonji commented on src/components/Home/Home.tsx
> -    };
今考えると元もプログラムもこの部分のコードあってもなくても変わらないのか…？ならisMountedはなんだったんだ？？？

2022-02-11 02:48 UTC, yochimonji approved these changes
👍

2022-02-11 02:49 UTC, merged